version: '3'

services:
  nginx0:
    image: nginx:1.16
    volumes:
      - "./nginx_data/html/:/usr/share/nginx/html"
      - "./nginx_data/conf_d:/etc/nginx/conf.d"
      - "./nginx_data/logs:/var/log/nginx/"
      - "./ssl:/etc/nginx/ssl"
    restart: always
    ports:
      - "2234:80" # test port like a 2234
      # - "443:443"
    networks:
      - example_svn_server_net
  svn_server:
    image: sea5kg/svn-server
    environment:
      - SVN_SERVER_REPOSITORIES_URL: /source/svn
    # ports:
    #   - "8011:80" # test web port 
    volumes:
      - "./svn/svnadmin_data:/opt/svnadmin/data:rw"
      - "./svn/repo:/home/svn"
      - "./svn/subversion-access-control:/etc/subversion/subversion-access-control"
      - "./svn/passwd:/etc/subversion/passwd"
    restart: always
    networks:
      - example_svn_server_net
networks:
    example_svn_server_net:
    driver: bridge
