name: Docker Image CI

on:
  push:
    branches:
      - 'master'
      - 'v[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
      - 'compose/**'
      - '.github/workflows/docker-description.yml'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - 'compose/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/svn-docker
        tags: |
          type=ref,event=branch
          type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/v') }}
        flavor: |
          latest=false
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      if: ${{ startsWith(github.ref, 'refs/heads/v') }}
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Build Docker image (fast)
      uses: docker/build-push-action@v4
      if: ${{ !startsWith(github.ref, 'refs/heads/v') }}
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
